site_name: Hack The Code
site_author: Open WEB
theme:
  name: material
  favicon: https://cdn0.iconfinder.com/data/icons/jam-vol-2/18/code-sample-1024.png
  logo: https://cdn0.iconfinder.com/data/icons/jam-vol-2/18/code-sample-1024.png
  font:
    text: Roboto Mono
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: green
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: neon green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - header.autohide
    - content.code.copy
    - navigation.top
    - navigation.footer
  toc:
    depth: 2


repo_name: learn-cpp
# repo_url: #
copyright: Copyright &copy; 2025 Coding
nav:
  - Home: index.md
  - Installation Databases:
      - MySQL: db.py
      - PostgreSQL: psql.py
  - Query Databases:
      - MySQL: m.py
      - PostgreSQL: p.py
  - Conditionals: hello.md
  - Attacks:
      - Network attacks: n.py
      - Web attacks: w.py
  - Python: py.md

plugins:
  - search
  #- tags
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
#  - glightbox:
#      auto_caption: true
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji
extra:
  social:
    - icon: fontawesome/solid/house
      # link: #
    - icon: fontawesome/brands/github
      # link: #
    - icon: fontawesome/solid/paper-plane
      # link: #
extra_css:
  - extra.css